### ISSUE TITLE
Proximos Passos

### ISSUE THREAD

**Issue by pauloxsdev** [deene7/KronosTech#1]
### CSS (admin)
> arrumar sidebar
> estilizar botões do "**Produtos**" e **"Pedidos"**

### php (user)
> colocar paginação do admin

### php (admin)
> contador de pedidos, produtos e clientes no dashboard.php (talvez)

**Comment by deene7** [comment]
**FIXED**
**> CSS (admin)**
> 
> arrumar sidebar
> estilizar botões do "Produtos" e "Pedidos"
